with open('index.html') as f:
    html = f.read()

# ── 1. CSS — scope toggle buttons ─────────────────────────────────────────────
old1 = '.comp-placeholder p{font-size:13px;color:var(--soft);margin-bottom:10px}'
new1 = (
    '.comp-placeholder p{font-size:13px;color:var(--soft);margin-bottom:10px}\n'
    '.comp-scope-toggle{display:flex;gap:6px;margin-bottom:14px}\n'
    '.scope-btn{background:var(--bg);border:1px solid var(--gL);color:var(--soft);padding:5px 14px;border-radius:20px;font-size:11px;cursor:pointer;font-family:inherit;letter-spacing:.3px;transition:all .15s}\n'
    '.scope-btn.active{background:var(--dark);border-color:var(--dark);color:#fff;font-weight:600}'
)
assert old1 in html, 'CSS anchor missing'
html = html.replace(old1, new1, 1)
print('✓ CSS')

# ── 2. HTML — toggle after Roster Comparison panel-title ──────────────────────
old2 = (
    '      <div class="panel-title">Roster Comparison</div>\n'
    '      <div id="comp-instructions">'
)
new2 = (
    '      <div class="panel-title">Roster Comparison</div>\n'
    '      <div class="comp-scope-toggle" id="comp-scope-toggle" style="display:none">\n'
    '        <button class="scope-btn active" id="btn-scope-harvard" onclick="setIvyMode(false)">Harvard</button>\n'
    '        <button class="scope-btn" id="btn-scope-ivy" onclick="setIvyMode(true)">Ivy League</button>\n'
    '      </div>\n'
    '      <div id="comp-instructions">'
)
assert old2 in html, 'HTML panel-title anchor missing'
html = html.replace(old2, new2, 1)
print('✓ HTML toggle')

# ── 3. Global IVY_MODE ────────────────────────────────────────────────────────
old3 = 'let IVY_COMP = null;\n'
new3 = 'let IVY_COMP = null;\nlet IVY_MODE = false;\n'
assert old3 in html, 'IVY_COMP global anchor missing'
html = html.replace(old3, new3, 1)
print('✓ IVY_MODE global')

# ── 4. Replace showComparison (prepend ivyPool + setIvyMode) ──────────────────
old4 = (
    "function showComparison(key) {\n"
    "  const cfg = CHART_CFGS[key];\n"
    "  document.getElementById('comp-instructions').style.display = 'none';\n"
    "  document.getElementById('comp-chart-area').style.display = 'block';\n"
    "  document.getElementById('chart-title').textContent = cfg.label || key;\n"
    "  const noteEl = document.getElementById('chart-note');\n"
    "  const guideEl = document.getElementById('chart-guide');\n"
    "  if (cfg.type === 'rank') {\n"
    "    const curVal = CUR.s26[cfg.key] ?? 0;\n"
    "    const rank = PLAYERS.filter(p => {\n"
    "      const v = p.s26[cfg.key] ?? 0;\n"
    "      return cfg.lowerBetter ? v < curVal : v > curVal;\n"
    "    }).length + 1;\n"
    "    const suffix = cfg.lowerBetter ? ' · Lower is better' : '';\n"
    "    noteEl.textContent = `${CUR.info.name.split(' ').slice(-1)[0]} ranks #${rank} of ${PLAYERS.length} on the roster${suffix}`;\n"
    "    guideEl.textContent = '';\n"
    "    guideEl.style.display = 'none';\n"
    "  } else {\n"
    "    noteEl.textContent = '';\n"
    "    guideEl.textContent = cfg.guide ? cfg.guide.note : '';\n"
    "    guideEl.style.display = cfg.guide ? 'block' : 'none';\n"
    "  }\n"
    "\n"
    "  if (compChart) { compChart.destroy(); compChart = null; }\n"
    "  const ctx = document.getElementById('comp-chart').getContext('2d');\n"
    "\n"
    "  if (cfg.type === 'rank') {\n"
    "    renderRankChart(ctx, cfg);\n"
    "  } else {\n"
    "    renderScatterChart(ctx, cfg);\n"
    "  }\n"
    "}"
)
new4 = (
    "function ivyPool() {\n"
    "  const harv = PLAYERS.map(p => ({info:p.info, s26:p.s26, _ref:p, _school:'Harvard'}));\n"
    "  const others = Object.entries(IVY_LEAGUE).flatMap(([, players]) =>\n"
    "    players.map(p => ({info:p.info, s26:p.s26, _ref:p, _school:p.info.school}))\n"
    "  );\n"
    "  return [...harv, ...others];\n"
    "}\n"
    "\n"
    "function setIvyMode(mode) {\n"
    "  IVY_MODE = mode;\n"
    "  if (activeChartKey) showComparison(activeChartKey);\n"
    "}\n"
    "\n"
    "function showComparison(key) {\n"
    "  const cfg = CHART_CFGS[key];\n"
    "  document.getElementById('comp-instructions').style.display = 'none';\n"
    "  document.getElementById('comp-chart-area').style.display = 'block';\n"
    "  const toggle = document.getElementById('comp-scope-toggle');\n"
    "  toggle.style.display = 'flex';\n"
    "  document.getElementById('btn-scope-harvard').classList.toggle('active', !IVY_MODE);\n"
    "  document.getElementById('btn-scope-ivy').classList.toggle('active', IVY_MODE);\n"
    "  document.getElementById('chart-title').textContent = cfg.label || key;\n"
    "  const noteEl = document.getElementById('chart-note');\n"
    "  const guideEl = document.getElementById('chart-guide');\n"
    "  if (cfg.type === 'rank') {\n"
    "    const pool = IVY_MODE ? ivyPool() : PLAYERS;\n"
    "    const curVal = CUR.s26[cfg.key] ?? 0;\n"
    "    const rank = pool.filter(p => {\n"
    "      const v = p.s26[cfg.key] ?? 0;\n"
    "      return cfg.lowerBetter ? v < curVal : v > curVal;\n"
    "    }).length + 1;\n"
    "    const suffix = cfg.lowerBetter ? ' · Lower is better' : '';\n"
    "    const scope = IVY_MODE ? `the Ivy League (${pool.length} players)` : `the roster`;\n"
    "    noteEl.textContent = `${CUR.info.name.split(' ').slice(-1)[0]} ranks #${rank} of ${pool.length} in ${scope}${suffix}`;\n"
    "    guideEl.textContent = '';\n"
    "    guideEl.style.display = 'none';\n"
    "  } else {\n"
    "    noteEl.textContent = '';\n"
    "    guideEl.textContent = cfg.guide ? cfg.guide.note : '';\n"
    "    guideEl.style.display = cfg.guide ? 'block' : 'none';\n"
    "  }\n"
    "\n"
    "  if (compChart) { compChart.destroy(); compChart = null; }\n"
    "  const ctx = document.getElementById('comp-chart').getContext('2d');\n"
    "\n"
    "  if (cfg.type === 'rank') {\n"
    "    renderRankChart(ctx, cfg);\n"
    "  } else {\n"
    "    renderScatterChart(ctx, cfg);\n"
    "  }\n"
    "}"
)
assert old4 in html, 'showComparison anchor missing'
html = html.replace(old4, new4, 1)
print('✓ ivyPool + setIvyMode + showComparison')

# ── 5. Replace renderRankChart ─────────────────────────────────────────────────
old5 = (
    "function renderRankChart(ctx, cfg) {\n"
    "  const {key, lowerBetter, fmt} = cfg;\n"
    "  const fmtFn = fmt === 'bpm' ? v => (v>=0?'+':'')+v.toFixed(1) : v => v.toFixed(1);\n"
    "  const entries = PLAYERS.map(p => ({\n"
    "    name: p.info.name.split(' ').slice(-1)[0],\n"
    "    val: p.s26[key] ?? 0,\n"
    "    isSel: p === CUR,\n"
    "    isComp: p === COMP,\n"
    "  })).sort((a,b) => lowerBetter ? a.val - b.val : b.val - a.val);\n"
    "\n"
    "  compChart = new Chart(ctx, {\n"
    "    type: 'bar',\n"
    "    data: {\n"
    "      labels: entries.map(e => e.name),\n"
    "      datasets: [{\n"
    "        data: entries.map(e => e.val),\n"
    "        backgroundColor: entries.map(e => e.isSel ? '#A41034' : e.isComp ? 'rgba(37,99,235,0.75)' : '#D4CCC7'),\n"
    "        borderRadius: 3,\n"
    "        barThickness: 14,\n"
    "      }]\n"
    "    },\n"
    "    options: {\n"
    "      indexAxis: 'y',\n"
    "      responsive: true, maintainAspectRatio: false,\n"
    "      plugins: {\n"
    "        legend: {display:false},\n"
    "        tooltip: {callbacks:{label: ctx => ' '+fmtFn(ctx.parsed.x)}}\n"
    "      },\n"
    "      scales: {\n"
    "        x: {grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "        y: {grid:{display:false}, ticks:{font:{size:11,weight: entry => entries[entry.index]?.isSel ? 'bold':'normal'}}}\n"
    "      }\n"
    "    }\n"
    "  });\n"
    "}"
)
new5 = (
    "function renderRankChart(ctx, cfg) {\n"
    "  const {key, lowerBetter, fmt} = cfg;\n"
    "  const fmtFn = fmt === 'bpm' ? v => (v>=0?'+':'')+v.toFixed(1) : v => v.toFixed(1);\n"
    "\n"
    "  if (!IVY_MODE) {\n"
    "    const entries = PLAYERS.map(p => ({\n"
    "      name: p.info.name.split(' ').slice(-1)[0],\n"
    "      val: p.s26[key] ?? 0,\n"
    "      isSel: p === CUR,\n"
    "      isComp: p === COMP,\n"
    "    })).sort((a,b) => lowerBetter ? a.val - b.val : b.val - a.val);\n"
    "    compChart = new Chart(ctx, {\n"
    "      type: 'bar',\n"
    "      data: {\n"
    "        labels: entries.map(e => e.name),\n"
    "        datasets: [{\n"
    "          data: entries.map(e => e.val),\n"
    "          backgroundColor: entries.map(e => e.isSel ? '#A41034' : e.isComp ? 'rgba(37,99,235,0.75)' : '#D4CCC7'),\n"
    "          borderRadius: 3,\n"
    "          barThickness: 14,\n"
    "        }]\n"
    "      },\n"
    "      options: {\n"
    "        indexAxis: 'y',\n"
    "        responsive: true, maintainAspectRatio: false,\n"
    "        plugins: {\n"
    "          legend: {display:false},\n"
    "          tooltip: {callbacks:{label: ctx => ' '+fmtFn(ctx.parsed.x)}}\n"
    "        },\n"
    "        scales: {\n"
    "          x: {grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "          y: {grid:{display:false}, ticks:{font:{size:11,weight: entry => entries[entry.index]?.isSel ? 'bold':'normal'}}}\n"
    "        }\n"
    "      }\n"
    "    });\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  const raw = ivyPool().map(p => ({\n"
    "    name: p.info.name.split(' ').slice(-1)[0],\n"
    "    school: p._school,\n"
    "    val: p.s26[key] ?? 0,\n"
    "    isSel:     p._ref === CUR,\n"
    "    isComp:    !!COMP     && p._ref === COMP,\n"
    "    isIvyComp: !!IVY_COMP && p._ref === IVY_COMP,\n"
    "    isHarvard: p._school === 'Harvard',\n"
    "  })).sort((a,b) => lowerBetter ? a.val - b.val : b.val - a.val);\n"
    "  raw.forEach((e,i) => { e.rank = i + 1; });\n"
    "\n"
    "  const dotColor = e => e.isSel ? '#A41034' : e.isComp ? 'rgba(37,99,235,0.85)' : e.isIvyComp ? 'rgba(180,120,40,0.9)' : e.isHarvard ? 'rgba(164,16,52,0.4)' : 'rgba(155,148,144,0.45)';\n"
    "  const dotR     = e => (e.isSel || e.isComp || e.isIvyComp) ? 9 : 5;\n"
    "  const bg = raw.filter(e => !e.isSel && !e.isComp && !e.isIvyComp);\n"
    "  const hi = raw.filter(e =>  e.isSel ||  e.isComp ||  e.isIvyComp);\n"
    "  const toXY = e => ({x:e.rank, y:e.val, name:e.name, school:e.school});\n"
    "\n"
    "  compChart = new Chart(ctx, {\n"
    "    type: 'scatter',\n"
    "    data: {\n"
    "      datasets: [\n"
    "        {data:bg.map(toXY), backgroundColor:bg.map(dotColor), pointRadius:bg.map(dotR), pointHoverRadius:bg.map(e=>dotR(e)+2)},\n"
    "        {data:hi.map(toXY), backgroundColor:hi.map(dotColor), pointRadius:hi.map(dotR), pointHoverRadius:hi.map(e=>dotR(e)+2)},\n"
    "      ]\n"
    "    },\n"
    "    options: {\n"
    "      responsive:true, maintainAspectRatio:false,\n"
    "      plugins: {\n"
    "        legend:{display:false},\n"
    "        tooltip:{callbacks:{label:c=>` ${c.raw.name} (${c.raw.school}): ${fmtFn(c.raw.y)}`}}\n"
    "      },\n"
    "      scales: {\n"
    "        x:{title:{display:true,text:'← Best · Rank in Ivy League · Worst →',font:{size:10}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11},callback:v=>'#'+v}},\n"
    "        y:{title:{display:true,text:cfg.label,font:{size:10}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11},callback:v=>fmtFn(v)}},\n"
    "      }\n"
    "    }\n"
    "  });\n"
    "}"
)
assert old5 in html, 'renderRankChart anchor missing'
html = html.replace(old5, new5, 1)
print('✓ renderRankChart')

# ── 6. Replace renderScatterChart ─────────────────────────────────────────────
old6 = (
    "function renderScatterChart(ctx, cfg) {\n"
    "  const {xKey, yKey, xLabel, yLabel, xFmt, yFmt} = cfg;\n"
    "  const xF = xFmt || (v => v.toFixed(1));\n"
    "  const yF = yFmt || (v => v.toFixed(1));\n"
    "\n"
    "  const others = PLAYERS.filter(p => p !== CUR && p !== COMP).map(p => ({\n"
    "    x: p.s26[xKey] ?? 0, y: p.s26[yKey] ?? 0, name: p.info.name.split(' ').slice(-1)[0]\n"
    "  }));\n"
    "  const sel = [{x: CUR.s26[xKey] ?? 0, y: CUR.s26[yKey] ?? 0, name: CUR.info.name.split(' ').slice(-1)[0]}];\n"
    "  const compDot = COMP ? [{x: COMP.s26[xKey] ?? 0, y: COMP.s26[yKey] ?? 0, name: COMP.info.name.split(' ').slice(-1)[0]}] : [];\n"
    "\n"
    "  const guidePlugin = makeGuidePlugin(cfg.guide);\n"
    "  compChart = new Chart(ctx, {\n"
    "    type: 'scatter',\n"
    "    data: {\n"
    "      datasets: [\n"
    "        {label:'Roster', data:others, backgroundColor:'rgba(155,148,144,0.55)', pointRadius:6, pointHoverRadius:8},\n"
    "        ...(COMP ? [{label:COMP.info.name, data:compDot, backgroundColor:'rgba(37,99,235,0.75)', pointRadius:9, pointHoverRadius:11}] : []),\n"
    "        {label:CUR.info.name, data:sel, backgroundColor:'#A41034', pointRadius:10, pointHoverRadius:12},\n"
    "      ]\n"
    "    },\n"
    "    options: {\n"
    "      responsive:true, maintainAspectRatio:false,\n"
    "      plugins: {\n"
    "        legend:{display:false},\n"
    "        tooltip:{callbacks:{\n"
    "          label: ctx => {\n"
    "            const d = ctx.raw;\n"
    "            return ` ${d.name}: ${xF(d.x)}, ${yF(d.y)}`;\n"
    "          }\n"
    "        }}\n"
    "      },\n"
    "      scales: {\n"
    "        x:{title:{display:true,text:xLabel,font:{size:11}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "        y:{title:{display:true,text:yLabel,font:{size:11}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "      }\n"
    "    },\n"
    "    plugins: guidePlugin ? [guidePlugin] : []\n"
    "  });\n"
    "}"
)
new6 = (
    "function renderScatterChart(ctx, cfg) {\n"
    "  const {xKey, yKey, xLabel, yLabel, xFmt, yFmt} = cfg;\n"
    "  const xF = xFmt || (v => v.toFixed(1));\n"
    "  const yF = yFmt || (v => v.toFixed(1));\n"
    "  const guidePlugin = makeGuidePlugin(cfg.guide);\n"
    "\n"
    "  if (!IVY_MODE) {\n"
    "    const others = PLAYERS.filter(p => p !== CUR && p !== COMP).map(p => ({\n"
    "      x: p.s26[xKey] ?? 0, y: p.s26[yKey] ?? 0, name: p.info.name.split(' ').slice(-1)[0]\n"
    "    }));\n"
    "    const sel = [{x: CUR.s26[xKey] ?? 0, y: CUR.s26[yKey] ?? 0, name: CUR.info.name.split(' ').slice(-1)[0]}];\n"
    "    const compDot = COMP ? [{x: COMP.s26[xKey] ?? 0, y: COMP.s26[yKey] ?? 0, name: COMP.info.name.split(' ').slice(-1)[0]}] : [];\n"
    "    compChart = new Chart(ctx, {\n"
    "      type: 'scatter',\n"
    "      data: {\n"
    "        datasets: [\n"
    "          {label:'Roster', data:others, backgroundColor:'rgba(155,148,144,0.55)', pointRadius:6, pointHoverRadius:8},\n"
    "          ...(COMP ? [{label:COMP.info.name, data:compDot, backgroundColor:'rgba(37,99,235,0.75)', pointRadius:9, pointHoverRadius:11}] : []),\n"
    "          {label:CUR.info.name, data:sel, backgroundColor:'#A41034', pointRadius:10, pointHoverRadius:12},\n"
    "        ]\n"
    "      },\n"
    "      options: {\n"
    "        responsive:true, maintainAspectRatio:false,\n"
    "        plugins: {\n"
    "          legend:{display:false},\n"
    "          tooltip:{callbacks:{label:ctx=>{const d=ctx.raw;return ` ${d.name}: ${xF(d.x)}, ${yF(d.y)}`;}}}\n"
    "        },\n"
    "        scales: {\n"
    "          x:{title:{display:true,text:xLabel,font:{size:11}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "          y:{title:{display:true,text:yLabel,font:{size:11}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "        }\n"
    "      },\n"
    "      plugins: guidePlugin ? [guidePlugin] : []\n"
    "    });\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  const pool = ivyPool().map(p => ({\n"
    "    x: p.s26[xKey] ?? 0, y: p.s26[yKey] ?? 0,\n"
    "    name: p.info.name.split(' ').slice(-1)[0],\n"
    "    school: p._school,\n"
    "    isSel:     p._ref === CUR,\n"
    "    isComp:    !!COMP     && p._ref === COMP,\n"
    "    isIvyComp: !!IVY_COMP && p._ref === IVY_COMP,\n"
    "    isHarvard: p._school === 'Harvard',\n"
    "  }));\n"
    "  const ivyOthers  = pool.filter(e => !e.isHarvard && !e.isComp && !e.isIvyComp && !e.isSel);\n"
    "  const harvOthers = pool.filter(e =>  e.isHarvard && !e.isComp && !e.isSel);\n"
    "  const compDots   = COMP     ? pool.filter(e => e.isComp)    : [];\n"
    "  const ivyCompDot = IVY_COMP ? pool.filter(e => e.isIvyComp) : [];\n"
    "  const selDot     = pool.filter(e => e.isSel);\n"
    "  compChart = new Chart(ctx, {\n"
    "    type: 'scatter',\n"
    "    data: {\n"
    "      datasets: [\n"
    "        {data:ivyOthers,  backgroundColor:'rgba(155,148,144,0.4)',  pointRadius:5, pointHoverRadius:7},\n"
    "        {data:harvOthers, backgroundColor:'rgba(164,16,52,0.35)',   pointRadius:5, pointHoverRadius:7},\n"
    "        ...(compDots.length   ? [{data:compDots,   backgroundColor:'rgba(37,99,235,0.85)',  pointRadius:9,  pointHoverRadius:11}] : []),\n"
    "        ...(ivyCompDot.length ? [{data:ivyCompDot, backgroundColor:'rgba(180,120,40,0.9)',  pointRadius:9,  pointHoverRadius:11}] : []),\n"
    "        {data:selDot, backgroundColor:'#A41034', pointRadius:11, pointHoverRadius:13},\n"
    "      ]\n"
    "    },\n"
    "    options: {\n"
    "      responsive:true, maintainAspectRatio:false,\n"
    "      plugins: {\n"
    "        legend:{display:false},\n"
    "        tooltip:{callbacks:{label:ctx=>{const d=ctx.raw;return ` ${d.name} (${d.school}): ${xF(d.x)}, ${yF(d.y)}`;}}}\n"
    "      },\n"
    "      scales: {\n"
    "        x:{title:{display:true,text:xLabel,font:{size:11}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "        y:{title:{display:true,text:yLabel,font:{size:11}}, grid:{color:'#F0EBE7'}, ticks:{font:{size:11}}},\n"
    "      }\n"
    "    },\n"
    "    plugins: guidePlugin ? [guidePlugin] : []\n"
    "  });\n"
    "}"
)
assert old6 in html, 'renderScatterChart anchor missing'
html = html.replace(old6, new6, 1)
print('✓ renderScatterChart')

with open('index.html', 'w') as f:
    f.write(html)

print('\nAll 6 patches applied.')
